# Funding platforms for sponsoring this project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
github: [DrBlury]
# Other platforms (uncomment and configure as needed)
# patreon: username
# open_collective: project-name
# ko_fi: username
# buy_me_a_coffee: username
# custom: ["https://your-custom-link.com"]
