# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "25...80"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  go:
    partials_as_hits: true

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "**/*.pb.go" # Generated protobuf files
  - "**/gen/**" # Generated code
  - "**/*_test.go" # Test files themselves
  - "main.go" # Application entry point
