services:
  app:
    container_name: mqtt-service-flow-example
    image: golang:1.25.1-alpine
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/src/:/app
      - .gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - ~/go/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    command: go run main.go
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - openobserve
      - kafka
    healthcheck:
      test: curl --fail -s localhost:8080/info/status || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: bitnami/kafka:3.5.0
    restart: unless-stopped
    volumes:
      - ./kafka-data:/bitnami/kafka
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka

  # broker:
  #   image: emqx:5
  #   container_name: broker
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883" # MQTT TCP
  #     - "8083:8083" # MQTT over WebSocket
  #     - "18083:18083" # Dashboard
  #   environment:
  #     # Keep it simple for local dev. For prod, disable anonymous and configure auth.
  #     EMQX_ALLOW_ANONYMOUS: "true"

  #     # Optional: set default dashboard creds (login at http://localhost:18083)
  #     EMQX_DASHBOARD__DEFAULT_USERNAME: "admin"
  #     EMQX_DASHBOARD__DEFAULT_PASSWORD: "public"
  #   volumes:
  #     - ./.emqx/data:/opt/emqx/data
  #     - ./.emqx/log:/opt/emqx/log

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
      RUST_LOG: error
    ports:
      - "5080:5080"
      - "5081:5081"
    volumes:
      - ./otel-data:/data
