---
version: 3

dotenv: ["./infra/env/app.env"]

tasks:
  gen-env-files:
    desc: "Generate all .env files from example folder into infra/env folder"
    cmds:
      - echo "Generating all .env files from example folder into infra/env folder"
      - cp infra/env/example/app.env.example infra/env/app.env
      - cp infra/env/example/kafdrop.env.example infra/env/kafdrop.env
      - cp infra/env/example/kafka.env.example infra/env/kafka.env
      - cp infra/env/example/mongo-express.env.example infra/env/mongo-express.env
      - cp infra/env/example/mongo.env.example infra/env/mongo.env
      - cp infra/env/example/openobserve.env.example infra/env/openobserve.env
      - cp infra/env/example/rabbitmq.env.example infra/env/rabbitmq.env
      - cp infra/env/example/localstack.env.example infra/env/localstack.env
    silent: true

  ci:
    desc: "Run all the github actions locally"
    cmds:
      - echo "Running all the github actions locally"
      - act | grep -v '::'
    silent: true

  act-test:
    desc: "Run the github action locally for some specific job"
    cmds:
      - echo "Running the github action locally for a specific job"
      - act --job ${JOB} | grep -v '::'
    silent: true

  debug:
    desc: "Start the app in debug mode using Delve (requires a running pubsub system)"
    cmds:
      - |
        echo "Starting the app in debug mode using Delve (requires a running pubsub system)"
        echo "Reading PUBSUB_SYSTEM from .env file! ${PUBSUB_SYSTEM}"
        if [ "${PUBSUB_SYSTEM}" = "kafka" ]; then
          echo "Using Kafka as pubsub system"
          docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.kafka.yml -f infra/compose/docker-compose.debug.yml up --build
        elif [ "${PUBSUB_SYSTEM}" = "rabbitmq" ]; then
          echo "Using RabbitMQ as pubsub system"
          docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.rabbitmq.yml -f infra/compose/docker-compose.debug.yml up --build
        elif [ "${PUBSUB_SYSTEM}" = "aws" ]; then
          echo "Using AWS/localstack as pubsub system"
          docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.aws.yml -f infra/compose/docker-compose.debug.yml up --build
        else
          echo "PUBSUB_SYSTEM is not set to a valid value (kafka, rabbitmq, aws) in .env file"
          exit 1
        fi
    silent: false

  up-rabbitmq:
    desc: "Start RabbitMQ runmode (app + mongo + rabbitmq)"
    cmds:
      - echo "Starting RabbitMQ mode (infra/compose/docker-compose.rabbitmq.yaml)"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.rabbitmq.yml up --build
    silent: true

  down-rabbitmq:
    desc: "Stop RabbitMQ runmode"
    cmds:
      - echo "Stopping RabbitMQ mode"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.rabbitmq.yml down
    silent: true

  up-kafka:
    desc: "Start Kafka runmode (app + mongo + kafka + kafdrop)"
    cmds:
      - echo "Starting Kafka mode (infra/compose/docker-compose.kafka.yaml)"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.kafka.yml up --build
    silent: true

  down-kafka:
    desc: "Stop Kafka runmode"
    cmds:
      - echo "Stopping Kafka mode"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.kafka.yml down
    silent: true

  up-aws:
    desc: "Start AWS/localstack runmode (app + mongo + localstack + openobserve)"
    cmds:
      - echo "Starting AWS/localstack mode (infra/compose/docker-compose.aws.yaml)"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.aws.yml up --build
    silent: true

  down-aws:
    desc: "Stop AWS/localstack runmode"
    cmds:
      - echo "Stopping AWS/localstack mode"
      - docker compose -f infra/compose/docker-compose.yml -f infra/compose/docker-compose.aws.yml down
    silent: true

  lint:
    desc: "Lint the project using golangci-lint"
    cmds:
      - echo "linting the project"
      - docker run --rm -v "./src:/code" golangci/golangci-lint:latest /bin/sh -c "cd /code && golangci-lint run"
    silent: true

  lint-api:
    desc: "Lint the api using redocly"
    cmds:
      - echo "Linting the api"
      - docker run --rm -v ./api/:/spec redocly/cli lint api.yml
    silent: true

  gen-api-std:
    desc: "Generate the api wrapper interfaces for std server using oapi-codegen"
    cmds:
      - echo "Generate the api wrapper interfaces for std server using oapi-codegen"
      - cd ./src/internal/server/handler/apihandler && go tool oapi-codegen -config ./server-std.cfg.yml ./embedded/openapi.json > ../../_gen/api.gen.go
    silent: true

  gen-api:
    desc: "Generate the api for the server using oapi-codegen"
    cmds:
      - echo "Generating the api for the server using oapi-codegen"
      - task lint-api
      - task gen-api-std
    silent: true

  gen-buf:
    desc: "Generate the go files from the protobuf definition using buf"
    cmds:
      - echo "Generating the go files from the protobuf definition"
      - docker build -t drblury/protobuf-gen-go -f ./proto/Dockerfile .
      - docker run --rm -v $(pwd):/workspace --workdir /workspace drblury/protobuf-gen-go generate
    silent: true

  install-tools:
    desc: "Install the local tools globally"
    cmds:
      - echo "Installing go based tools"
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - npm install -g @stoplight/prism-cli

  scc:
    desc: "Run scc to show stats"
    cmds:
      - echo "Running scc to show stats"
      - docker run --rm -it -v "$PWD:/pwd"  ghcr.io/lhoupert/scc:master scc /pwd
    silent: true
