---
version: 3

dotenv: [".env"]

tasks:
  gen-env-file:
    desc: "Generate the .env file"
    cmds:
      - echo "Generating the .env file"
      - cp .env.example .env
    silent: true

  start:
    desc: "Run the docker compose file"
    cmds:
      - echo "Starting the application with docker."
      - docker compose up --build
    silent: true

  build-image:
    desc: "Build the docker image"
    cmds:
      - echo "Building the docker image"
      - docker build -t cpc-contract-facade -f build/dockerfiles/Dockerfile.app .
    silent: true

  start-debug:
    desc: "Run the debug docker compose file"
    cmds:
      - echo "Starting the application with debug docker compose file."
      - docker compose -f docker-compose.yml up --build --no-log-prefix
      - echo "You can now connect delve via port 2345 to the container for remote debugging"
    silent: true

  lint:
    desc: "Lint the project using golangci-lint"
    cmds:
      - echo "linting the project"
      - docker run --rm -v "./src:/code" golangci/golangci-lint:latest /bin/sh -c "cd /code && golangci-lint run"
    silent: true

  lint-api:
    desc: "Lint the api using redocly"
    cmds:
      - echo "Linting the api"
      - docker run --rm -v ./api/:/spec redocly/cli lint api.yml
    silent: true

  bundle-api:
    desc: "Bundle the api using redocly"
    cmds:
      - echo "Bundling the api using redocly/redoc"
      - docker run --rm -v ./api/:/spec redocly/cli bundle api.yml -o bundle.yml
    silent: true

  gen-embedded-api:
    desc: "Generate the embedded json for the api"
    cmds:
      - echo "Generating the embedded json for the api"
      - docker run --rm -v ./api/:/spec redocly/cli bundle api.yml -o openapi.json
      - mv ./api/openapi.json ./src/internal/server/handler/apihandler/embedded/openapi.json
    silent: true

  # gen-api-std:
  #   desc: "Generate the api wrapper interfaces for std server using oapi-codegen"
  #   cmds:
  #     - echo "Generate the api wrapper interfaces for std server using oapi-codegen"
  #     - oapi-codegen --config ./api/server-std.cfg.yml ./api/bundle.yml > ./src/internal/server/generated/api.gen.go
  #   silent: true

  gen-api:
    desc: "Generate the api for the server using oapi-codegen"
    cmds:
      - echo "Generating the api for the server using oapi-codegen"
      - task lint-api
      - task bundle-api
      - task gen-embedded-api
      # - task gen-api-std
    silent: true

  gen-buf:
    desc: "Generate the go files from the protobuf definition using buf"
    cmds:
      - echo "Generating the go files from the protobuf definition"
      - docker build -t drblury/protobuf-gen-go -f ./build/dockerfiles/Dockerfile.protobuf .
      - docker run --rm -v $(pwd):/workspace --workdir /workspace drblury/protobuf-gen-go generate
    silent: true

  install-tools:
    desc: "Install the local tools globally"
    cmds:
      - echo "Installing go based tools"
      -  # for the binary install
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - npm install -g @stoplight/prism-cli

  scc:
    desc: "Run scc to show stats"
    cmds:
      - echo "Running scc to show stats"
      - docker run --rm -it -v "$PWD:/pwd"  ghcr.io/lhoupert/scc:master scc /pwd
    silent: true

  # gen-api-clients:
  #   desc: 'Generate the api clients for the services'
  #   cmds:
  #     - echo "Generating the api clients for the services"
  #     - cd ./src/internal/service/ibanvalidator/res && oapi-codegen -config cfg.yml oapi.json
  #     - cd ./src/internal/service/trpc/res && oapi-codegen -config cfg.yml oapi.json
  #     - cd ./src/internal/service/agenthint/res && oapi-codegen -config cfg.yml oapi.json
  #     - cd ./src/internal/service/postcd/res && oapi-codegen -config cfg.yml oapi.json
  #     - cd ./src/internal/service/signup-gateway/res && oapi-codegen -config cfg.yml oapi.json
  #   silent: true
