name: Lint Protobuf with Buf
description: Sets up Buf and lints protobuf files.
inputs:
  working-directory:
    description: Directory containing buf.yaml.
    required: false
    default: proto
  buf-version:
    description: Buf CLI version to install.
    required: false
    default: "1.60.0"
  github-token:
    description: GitHub token for Buf setup (optional, reduces rate limiting).
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Setup Buf
      uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf-version }}
        github_token: ${{ inputs.github-token }}

    - name: Run buf lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: buf lint
