name: Setup Node.js Environment
description: Sets up Node.js for tooling that requires it.
inputs:
  node-version:
    description: Node.js version to install.
    required: false
    default: "20"
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
