services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    environment:
      PUBSUB_SYSTEM: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../env/rabbitmq.env
    volumes:
      - ../_rabbitmq_data:/var/lib/rabbitmq
      - ../config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 3s
      timeout: 3s
      retries: 5
