#!/usr/bin/env bash
# Generate SCC (Sloc Cloc and Code) report for the codebase
# This script is called by the pre-commit hook to keep code metrics up to date

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/docs/code-metrics.md"
SCC_IMAGE="ghcr.io/lhoupert/scc:v0.0.2"

echo "Generating code metrics with SCC..."

# Create docs directory if it doesn't exist
mkdir -p "${REPO_ROOT}/docs"

# Generate the report with timestamp
{
    echo "# Code Metrics"
    echo ""
    echo "This file is automatically generated by the pre-commit hook using [scc](https://github.com/boyter/scc)."
    echo ""
    echo "**Last Updated:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo ""
    echo "## Overview"
    echo ""
    echo '```'
    docker run --rm -v "${REPO_ROOT}:/pwd" "${SCC_IMAGE}" scc /pwd
    echo '```'
    echo ""
    echo "## Metrics by File"
    echo ""
    echo "Per-file breakdown sorted by complexity (excluding test files):"
    echo ""
    echo '```'
    docker run --rm -v "${REPO_ROOT}:/pwd" "${SCC_IMAGE}" scc --by-file --sort complexity --exclude-file _test.go /pwd
    echo '```'
    echo ""
    echo "## Detailed Statistics"
    echo ""
    echo "For JSON format output, use:"
    echo '```bash'
    echo "task scc"
    echo '```'
    echo ""
    echo "Or run directly:"
    echo '```bash'
    echo "docker run --rm -v \"\$PWD:/pwd\" ${SCC_IMAGE} scc /pwd"
    echo '```'
} > "${OUTPUT_FILE}"

echo "Code metrics generated at ${OUTPUT_FILE}"

# Stage the updated file for commit
git add "${OUTPUT_FILE}"
