package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/samber/lo"
)

var sections = []struct {
	header string
	dir    string
}{
	{header: "# Enums", dir: "enum"},
	{header: "# Requests", dir: "requests"},
	{header: "# Types", dir: "types"},
	{header: "# Errors", dir: "errors"},
}

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}

	schemaDir := filepath.Join(root, "api", "schemas")
	if err := ensureDir(schemaDir); err != nil {
		fatal(err)
	}

	var buf bytes.Buffer
	buf.WriteString("---\n")
	buf.WriteString("# Generated by scripts/update-schema-index.go\n")
	buf.WriteString("# Run `go run ./scripts/update-schema-index.go` after adding schemas.\n\n")

	for _, section := range sections {
		entries, err := listSchemas(filepath.Join(schemaDir, section.dir))
		if err != nil {
			fatal(err)
		}
		if len(entries) == 0 {
			continue
		}
		buf.WriteString(section.header + "\n")
		for _, entry := range entries {
			relPath := fmt.Sprintf("./%s/%s.yml", section.dir, entry)
			buf.WriteString(fmt.Sprintf("%s:\n  $ref: \"%s\"\n\n", entry, relPath))
		}
	}

	target := filepath.Join(schemaDir, "_index.yml")
	if err := os.WriteFile(target, buf.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if cwd == "/" {
			return "", errors.New("repository root not found (looking for go.work)")
		}
		if _, err := os.Stat(filepath.Join(cwd, "go.work")); err == nil {
			return cwd, nil
		}
		next := filepath.Dir(cwd)
		if next == cwd {
			return "", errors.New("repository root not found")
		}
		cwd = next
	}
}

func ensureDir(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return errors.New(path + " is not a directory")
	}
	return nil
}

func listSchemas(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	names := lo.FilterMap(entries, func(entry fs.DirEntry, _ int) (string, bool) {
		if entry.IsDir() {
			return "", false
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".yml") {
			return "", false
		}
		trimmed := strings.TrimSuffix(name, ".yml")
		if trimmed == "_index" {
			return "", false
		}
		return trimmed, true
	})
	sort.Strings(names)
	return names, nil
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "update-schema-index: %v\n", err)
	os.Exit(1)
}
