// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: domain/address.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Street          *string                `protobuf:"bytes,1,opt,name=street,proto3,oneof" json:"street,omitempty"`
	HouseNumber     *string                `protobuf:"bytes,2,opt,name=houseNumber,proto3,oneof" json:"houseNumber,omitempty"`
	Zip             *string                `protobuf:"bytes,3,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	City            *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	StateOrProvince *string                `protobuf:"bytes,5,opt,name=stateOrProvince,proto3,oneof" json:"stateOrProvince,omitempty"`
	CareOf          *string                `protobuf:"bytes,6,opt,name=careOf,proto3,oneof" json:"careOf,omitempty"`
	AdditionalInfo  *string                `protobuf:"bytes,7,opt,name=additionalInfo,proto3,oneof" json:"additionalInfo,omitempty"`
	Country         *string                `protobuf:"bytes,8,opt,name=country,proto3,oneof" json:"country,omitempty"`
	PostBox         *string                `protobuf:"bytes,9,opt,name=postBox,proto3,oneof" json:"postBox,omitempty"`
	IsPreferred     *bool                  `protobuf:"varint,10,opt,name=isPreferred,proto3,oneof" json:"isPreferred,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_domain_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_domain_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_domain_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *Address) GetHouseNumber() string {
	if x != nil && x.HouseNumber != nil {
		return *x.HouseNumber
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Address) GetStateOrProvince() string {
	if x != nil && x.StateOrProvince != nil {
		return *x.StateOrProvince
	}
	return ""
}

func (x *Address) GetCareOf() string {
	if x != nil && x.CareOf != nil {
		return *x.CareOf
	}
	return ""
}

func (x *Address) GetAdditionalInfo() string {
	if x != nil && x.AdditionalInfo != nil {
		return *x.AdditionalInfo
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Address) GetPostBox() string {
	if x != nil && x.PostBox != nil {
		return *x.PostBox
	}
	return ""
}

func (x *Address) GetIsPreferred() bool {
	if x != nil && x.IsPreferred != nil {
		return *x.IsPreferred
	}
	return false
}

var File_domain_address_proto protoreflect.FileDescriptor

const file_domain_address_proto_rawDesc = "" +
	"\n" +
	"\x14domain/address.proto\x12\x06domain\"\xe1\x03\n" +
	"\aAddress\x12\x1b\n" +
	"\x06street\x18\x01 \x01(\tH\x00R\x06street\x88\x01\x01\x12%\n" +
	"\vhouseNumber\x18\x02 \x01(\tH\x01R\vhouseNumber\x88\x01\x01\x12\x15\n" +
	"\x03zip\x18\x03 \x01(\tH\x02R\x03zip\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x03R\x04city\x88\x01\x01\x12-\n" +
	"\x0fstateOrProvince\x18\x05 \x01(\tH\x04R\x0fstateOrProvince\x88\x01\x01\x12\x1b\n" +
	"\x06careOf\x18\x06 \x01(\tH\x05R\x06careOf\x88\x01\x01\x12+\n" +
	"\x0eadditionalInfo\x18\a \x01(\tH\x06R\x0eadditionalInfo\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\b \x01(\tH\aR\acountry\x88\x01\x01\x12\x1d\n" +
	"\apostBox\x18\t \x01(\tH\bR\apostBox\x88\x01\x01\x12%\n" +
	"\visPreferred\x18\n" +
	" \x01(\bH\tR\visPreferred\x88\x01\x01B\t\n" +
	"\a_streetB\x0e\n" +
	"\f_houseNumberB\x06\n" +
	"\x04_zipB\a\n" +
	"\x05_cityB\x12\n" +
	"\x10_stateOrProvinceB\t\n" +
	"\a_careOfB\x11\n" +
	"\x0f_additionalInfoB\n" +
	"\n" +
	"\b_countryB\n" +
	"\n" +
	"\b_postBoxB\x0e\n" +
	"\f_isPreferredB\n" +
	"Z\b./domainb\x06proto3"

var (
	file_domain_address_proto_rawDescOnce sync.Once
	file_domain_address_proto_rawDescData []byte
)

func file_domain_address_proto_rawDescGZIP() []byte {
	file_domain_address_proto_rawDescOnce.Do(func() {
		file_domain_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_address_proto_rawDesc), len(file_domain_address_proto_rawDesc)))
	})
	return file_domain_address_proto_rawDescData
}

var file_domain_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_address_proto_goTypes = []any{
	(*Address)(nil), // 0: domain.Address
}
var file_domain_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_address_proto_init() }
func file_domain_address_proto_init() {
	if File_domain_address_proto != nil {
		return
	}
	file_domain_address_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_address_proto_rawDesc), len(file_domain_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_address_proto_goTypes,
		DependencyIndexes: file_domain_address_proto_depIdxs,
		MessageInfos:      file_domain_address_proto_msgTypes,
	}.Build()
	File_domain_address_proto = out.File
	file_domain_address_proto_goTypes = nil
	file_domain_address_proto_depIdxs = nil
}
