// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: domain/customer.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_MALE    Gender = 0
	Gender_GENDER_FEMALE  Gender = 1
	Gender_GENDER_DIVERSE Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_MALE",
		1: "GENDER_FEMALE",
		2: "GENDER_DIVERSE",
	}
	Gender_value = map[string]int32{
		"GENDER_MALE":    0,
		"GENDER_FEMALE":  1,
		"GENDER_DIVERSE": 2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_customer_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_domain_customer_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_domain_customer_proto_rawDescGZIP(), []int{0}
}

type CustomerContact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContactEmail   *string                `protobuf:"bytes,1,opt,name=contactEmail,proto3,oneof" json:"contactEmail,omitempty"`
	ContactMobile  *string                `protobuf:"bytes,2,opt,name=contactMobile,proto3,oneof" json:"contactMobile,omitempty"`
	ContactPhone   *string                `protobuf:"bytes,3,opt,name=contactPhone,proto3,oneof" json:"contactPhone,omitempty"`
	BillingAddress *Address               `protobuf:"bytes,4,opt,name=billingAddress,proto3,oneof" json:"billingAddress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CustomerContact) Reset() {
	*x = CustomerContact{}
	mi := &file_domain_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerContact) ProtoMessage() {}

func (x *CustomerContact) ProtoReflect() protoreflect.Message {
	mi := &file_domain_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerContact.ProtoReflect.Descriptor instead.
func (*CustomerContact) Descriptor() ([]byte, []int) {
	return file_domain_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerContact) GetContactEmail() string {
	if x != nil && x.ContactEmail != nil {
		return *x.ContactEmail
	}
	return ""
}

func (x *CustomerContact) GetContactMobile() string {
	if x != nil && x.ContactMobile != nil {
		return *x.ContactMobile
	}
	return ""
}

func (x *CustomerContact) GetContactPhone() string {
	if x != nil && x.ContactPhone != nil {
		return *x.ContactPhone
	}
	return ""
}

func (x *CustomerContact) GetBillingAddress() *Address {
	if x != nil {
		return x.BillingAddress
	}
	return nil
}

type CustomerPersonal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *string                `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=firstName,proto3,oneof" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	MiddleName    *string                `protobuf:"bytes,4,opt,name=middleName,proto3,oneof" json:"middleName,omitempty"`
	Gender        Gender                 `protobuf:"varint,5,opt,name=gender,proto3,enum=domain.Gender" json:"gender,omitempty"`
	DateOfBirth   *Date                  `protobuf:"bytes,6,opt,name=dateOfBirth,proto3,oneof" json:"dateOfBirth,omitempty"`
	Online        *bool                  `protobuf:"varint,7,opt,name=online,proto3,oneof" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerPersonal) Reset() {
	*x = CustomerPersonal{}
	mi := &file_domain_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerPersonal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerPersonal) ProtoMessage() {}

func (x *CustomerPersonal) ProtoReflect() protoreflect.Message {
	mi := &file_domain_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerPersonal.ProtoReflect.Descriptor instead.
func (*CustomerPersonal) Descriptor() ([]byte, []int) {
	return file_domain_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerPersonal) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CustomerPersonal) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *CustomerPersonal) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CustomerPersonal) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *CustomerPersonal) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_MALE
}

func (x *CustomerPersonal) GetDateOfBirth() *Date {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *CustomerPersonal) GetOnline() bool {
	if x != nil && x.Online != nil {
		return *x.Online
	}
	return false
}

var File_domain_customer_proto protoreflect.FileDescriptor

const file_domain_customer_proto_rawDesc = "" +
	"\n" +
	"\x15domain/customer.proto\x12\x06domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11domain/date.proto\x1a\x14domain/address.proto\"\x93\x02\n" +
	"\x0fCustomerContact\x12'\n" +
	"\fcontactEmail\x18\x01 \x01(\tH\x00R\fcontactEmail\x88\x01\x01\x12)\n" +
	"\rcontactMobile\x18\x02 \x01(\tH\x01R\rcontactMobile\x88\x01\x01\x12'\n" +
	"\fcontactPhone\x18\x03 \x01(\tH\x02R\fcontactPhone\x88\x01\x01\x12<\n" +
	"\x0ebillingAddress\x18\x04 \x01(\v2\x0f.domain.AddressH\x03R\x0ebillingAddress\x88\x01\x01B\x0f\n" +
	"\r_contactEmailB\x10\n" +
	"\x0e_contactMobileB\x0f\n" +
	"\r_contactPhoneB\x11\n" +
	"\x0f_billingAddress\"\xcd\x02\n" +
	"\x10CustomerPersonal\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12!\n" +
	"\tfirstName\x18\x02 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"middleName\x18\x04 \x01(\tH\x02R\n" +
	"middleName\x88\x01\x01\x12&\n" +
	"\x06gender\x18\x05 \x01(\x0e2\x0e.domain.GenderR\x06gender\x123\n" +
	"\vdateOfBirth\x18\x06 \x01(\v2\f.domain.DateH\x03R\vdateOfBirth\x88\x01\x01\x12\x1b\n" +
	"\x06online\x18\a \x01(\bH\x04R\x06online\x88\x01\x01B\b\n" +
	"\x06_titleB\f\n" +
	"\n" +
	"_firstNameB\r\n" +
	"\v_middleNameB\x0e\n" +
	"\f_dateOfBirthB\t\n" +
	"\a_online*@\n" +
	"\x06Gender\x12\x0f\n" +
	"\vGENDER_MALE\x10\x00\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x01\x12\x12\n" +
	"\x0eGENDER_DIVERSE\x10\x02B\n" +
	"Z\b./domainb\x06proto3"

var (
	file_domain_customer_proto_rawDescOnce sync.Once
	file_domain_customer_proto_rawDescData []byte
)

func file_domain_customer_proto_rawDescGZIP() []byte {
	file_domain_customer_proto_rawDescOnce.Do(func() {
		file_domain_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_customer_proto_rawDesc), len(file_domain_customer_proto_rawDesc)))
	})
	return file_domain_customer_proto_rawDescData
}

var file_domain_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_customer_proto_goTypes = []any{
	(Gender)(0),              // 0: domain.Gender
	(*CustomerContact)(nil),  // 1: domain.CustomerContact
	(*CustomerPersonal)(nil), // 2: domain.CustomerPersonal
	(*Address)(nil),          // 3: domain.Address
	(*Date)(nil),             // 4: domain.Date
}
var file_domain_customer_proto_depIdxs = []int32{
	3, // 0: domain.CustomerContact.billingAddress:type_name -> domain.Address
	0, // 1: domain.CustomerPersonal.gender:type_name -> domain.Gender
	4, // 2: domain.CustomerPersonal.dateOfBirth:type_name -> domain.Date
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_customer_proto_init() }
func file_domain_customer_proto_init() {
	if File_domain_customer_proto != nil {
		return
	}
	file_domain_date_proto_init()
	file_domain_address_proto_init()
	file_domain_customer_proto_msgTypes[0].OneofWrappers = []any{}
	file_domain_customer_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_customer_proto_rawDesc), len(file_domain_customer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_customer_proto_goTypes,
		DependencyIndexes: file_domain_customer_proto_depIdxs,
		EnumInfos:         file_domain_customer_proto_enumTypes,
		MessageInfos:      file_domain_customer_proto_msgTypes,
	}.Build()
	File_domain_customer_proto = out.File
	file_domain_customer_proto_goTypes = nil
	file_domain_customer_proto_depIdxs = nil
}
