// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: domain/v1/example.proto

package domain

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExampleRecord demonstrates the payload this sample service works with.
//
// Validation showcase:
//   - record_id: non-empty string with UUID format (CEL regex — impossible in plain JSON Schema)
//   - title: 3–100 characters (built-in range constraint)
//   - description: optional, max 500 characters
//   - tags: at most 10 items, each 1–30 characters, no duplicates (CEL all+filter — CEL advantage)
//   - cross-field CEL: when tags are provided, meta.requested_by must be set
type ExampleRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RecordId    string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId" json:"record_id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Meta        *ExampleMeta           `protobuf:"bytes,4,opt,name=meta" json:"meta,omitempty"`
	// CEL uniqueness check via all()+filter() — not expressible in OpenAPI JSON Schema
	Tags          []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleRecord) Reset() {
	*x = ExampleRecord{}
	mi := &file_domain_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRecord) ProtoMessage() {}

func (x *ExampleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRecord.ProtoReflect.Descriptor instead.
func (*ExampleRecord) Descriptor() ([]byte, []int) {
	return file_domain_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ExampleRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExampleRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExampleRecord) GetMeta() *ExampleMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ExampleRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ExampleMeta groups together additional sample fields.
//
// Validation showcase:
//   - requested_by: 2–64 characters, only alphanumeric/dots/underscores/hyphens (CEL regex)
//   - priority: 1–5 range (built-in int constraint)
//   - desired_start_date: when present, year must be ≥ 2020 (message-level CEL on nested field)
//   - cross-field CEL: if requires_follow_up is true, priority must be ≥ 3
//     (impossible with field-level OpenAPI validation alone)
type ExampleMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestedBy      string                 `protobuf:"bytes,1,opt,name=requested_by,json=requestedBy" json:"requested_by,omitempty"`
	DesiredStartDate *date.Date             `protobuf:"bytes,2,opt,name=desired_start_date,json=desiredStartDate" json:"desired_start_date,omitempty"`
	RequiresFollowUp bool                   `protobuf:"varint,3,opt,name=requires_follow_up,json=requiresFollowUp" json:"requires_follow_up,omitempty"`
	Priority         int32                  `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExampleMeta) Reset() {
	*x = ExampleMeta{}
	mi := &file_domain_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMeta) ProtoMessage() {}

func (x *ExampleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMeta.ProtoReflect.Descriptor instead.
func (*ExampleMeta) Descriptor() ([]byte, []int) {
	return file_domain_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleMeta) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *ExampleMeta) GetDesiredStartDate() *date.Date {
	if x != nil {
		return x.DesiredStartDate
	}
	return nil
}

func (x *ExampleMeta) GetRequiresFollowUp() bool {
	if x != nil {
		return x.RequiresFollowUp
	}
	return false
}

func (x *ExampleMeta) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ExampleResult is emitted by event handlers once the record was processed.
//
// Validation showcase:
//   - record_id: UUID format (same rule reused — proto annotation DRY)
//   - status: must be one of a fixed set (CEL `in` operator — enum-like without proto enum)
//   - note: optional, max 1000 characters
//   - cross-field CEL: when status is "failed", note must explain the failure reason
//     (conditional requirement — not possible in field-level OpenAPI validation)
type ExampleResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RecordId string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId" json:"record_id,omitempty"`
	// CEL `in` operator validates against an allowed set — cleaner than multiple enum values
	Status        string     `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Note          string     `protobuf:"bytes,3,opt,name=note" json:"note,omitempty"`
	ProcessedOn   *date.Date `protobuf:"bytes,4,opt,name=processed_on,json=processedOn" json:"processed_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResult) Reset() {
	*x = ExampleResult{}
	mi := &file_domain_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResult) ProtoMessage() {}

func (x *ExampleResult) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResult.ProtoReflect.Descriptor instead.
func (*ExampleResult) Descriptor() ([]byte, []int) {
	return file_domain_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleResult) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ExampleResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExampleResult) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ExampleResult) GetProcessedOn() *date.Date {
	if x != nil {
		return x.ProcessedOn
	}
	return nil
}

var File_domain_v1_example_proto protoreflect.FileDescriptor

const file_domain_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x17domain/v1/example.proto\x12\tdomain.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/descriptor.proto\x1a\x16google/type/date.proto\"\xb4\x05\n" +
	"\rExampleRecord\x12\xe9\x01\n" +
	"\trecord_id\x18\x01 \x01(\tB\xcb\x01\xbaH\xc7\x01\xba\x01\xbd\x01\n" +
	"\x15record_id.uuid_format\x12Erecord_id must be a valid UUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)\x1a]this.matches('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')r\x04\x10\x01\x18$R\brecordId\x12\x1f\n" +
	"\x05title\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18dR\x05title\x12-\n" +
	"\vdescription\x18\x03 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\x18\xf4\x03R\vdescription\x12*\n" +
	"\x04meta\x18\x04 \x01(\v2\x16.domain.v1.ExampleMetaR\x04meta\x12\x9b\x01\n" +
	"\x04tags\x18\x05 \x03(\tB\x86\x01\xbaH\x82\x01\xba\x01r\n" +
	"\x12tags.no_duplicates\x12+tags must be unique (no duplicates allowed)\x1a/this.all(x, this.filter(y, y == x).size() == 1)\x92\x01\n" +
	"\x10\n" +
	"\"\x06r\x04\x10\x01\x18\x1eR\x04tags:\x9c\x01\xbaH\x98\x01\x1a\x95\x01\n" +
	" example_record.tags_require_meta\x125meta.requested_by must be set when tags are specified\x1a:this.tags.size() == 0 || this.meta.requested_by.size() > 0\"\x8d\x05\n" +
	"\vExampleMeta\x12\xb9\x01\n" +
	"\frequested_by\x18\x01 \x01(\tB\x95\x01\xbaH\x91\x01\xba\x01\x87\x01\n" +
	"\x13requested_by.format\x12Mrequested_by must contain only letters, digits, dots, underscores, or hyphens\x1a!this.matches('^[a-zA-Z0-9._-]+$')r\x04\x10\x02\x18@R\vrequestedBy\x12?\n" +
	"\x12desired_start_date\x18\x02 \x01(\v2\x11.google.type.DateR\x10desiredStartDate\x12,\n" +
	"\x12requires_follow_up\x18\x03 \x01(\bR\x10requiresFollowUp\x12%\n" +
	"\bpriority\x18\x04 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x05(\x01R\bpriority:\xab\x02\xbaH\xa7\x02\x1a\x89\x01\n" +
	"\x1fexample_meta.follow_up_priority\x126priority must be at least 3 when follow-up is required\x1a.!this.requires_follow_up || this.priority >= 3\x1a\x98\x01\n" +
	" example_meta.start_date_min_year\x12-desired_start_date year must be 2020 or later\x1aE!has(this.desired_start_date) || this.desired_start_date.year >= 2020\"\xb3\x05\n" +
	"\rExampleResult\x12\xf0\x01\n" +
	"\trecord_id\x18\x01 \x01(\tB\xd2\x01\xbaH\xce\x01\xba\x01\xc4\x01\n" +
	"\x1cresult_record_id.uuid_format\x12Erecord_id must be a valid UUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)\x1a]this.matches('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')r\x04\x10\x01\x18$R\brecordId\x12\xae\x01\n" +
	"\x06status\x18\x02 \x01(\tB\x95\x01\xbaH\x91\x01\xba\x01\x8d\x01\n" +
	"\x12status.valid_value\x12=status must be one of: pending, processing, completed, failed\x1a8this in ['pending', 'processing', 'completed', 'failed']R\x06status\x12\x1f\n" +
	"\x04note\x18\x03 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\x18\xe8\aR\x04note\x124\n" +
	"\fprocessed_on\x18\x04 \x01(\v2\x11.google.type.DateR\vprocessedOn:\xa6\x01\xbaH\xa2\x01\x1a\x9f\x01\n" +
	"#example_result.failed_requires_note\x12Gnote is required when status is 'failed' to describe the failure reason\x1a/this.status != 'failed' || this.note.size() > 0B3Z,drblury/event-driven-service/internal/domain\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_domain_v1_example_proto_rawDescOnce sync.Once
	file_domain_v1_example_proto_rawDescData []byte
)

func file_domain_v1_example_proto_rawDescGZIP() []byte {
	file_domain_v1_example_proto_rawDescOnce.Do(func() {
		file_domain_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_v1_example_proto_rawDesc), len(file_domain_v1_example_proto_rawDesc)))
	})
	return file_domain_v1_example_proto_rawDescData
}

var file_domain_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_v1_example_proto_goTypes = []any{
	(*ExampleRecord)(nil), // 0: domain.v1.ExampleRecord
	(*ExampleMeta)(nil),   // 1: domain.v1.ExampleMeta
	(*ExampleResult)(nil), // 2: domain.v1.ExampleResult
	(*date.Date)(nil),     // 3: google.type.Date
}
var file_domain_v1_example_proto_depIdxs = []int32{
	1, // 0: domain.v1.ExampleRecord.meta:type_name -> domain.v1.ExampleMeta
	3, // 1: domain.v1.ExampleMeta.desired_start_date:type_name -> google.type.Date
	3, // 2: domain.v1.ExampleResult.processed_on:type_name -> google.type.Date
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_v1_example_proto_init() }
func file_domain_v1_example_proto_init() {
	if File_domain_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_example_proto_rawDesc), len(file_domain_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_v1_example_proto_goTypes,
		DependencyIndexes: file_domain_v1_example_proto_depIdxs,
		MessageInfos:      file_domain_v1_example_proto_msgTypes,
	}.Build()
	File_domain_v1_example_proto = out.File
	file_domain_v1_example_proto_goTypes = nil
	file_domain_v1_example_proto_depIdxs = nil
}
