// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: domain/Info.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	BuildDate     string                 `protobuf:"bytes,2,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	CommitHash    string                 `protobuf:"bytes,4,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	CommitDate    string                 `protobuf:"bytes,5,opt,name=commitDate,proto3" json:"commitDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_domain_Info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_domain_Info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_domain_Info_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *Info) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Info) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *Info) GetCommitDate() string {
	if x != nil {
		return x.CommitDate
	}
	return ""
}

var File_domain_Info_proto protoreflect.FileDescriptor

const file_domain_Info_proto_rawDesc = "" +
	"\n" +
	"\x11domain/Info.proto\x12\x06domain\"\x98\x01\n" +
	"\x04Info\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\tbuildDate\x18\x02 \x01(\tR\tbuildDate\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1e\n" +
	"\n" +
	"commitHash\x18\x04 \x01(\tR\n" +
	"commitHash\x12\x1e\n" +
	"\n" +
	"commitDate\x18\x05 \x01(\tR\n" +
	"commitDateB\n" +
	"Z\b./domainb\x06proto3"

var (
	file_domain_Info_proto_rawDescOnce sync.Once
	file_domain_Info_proto_rawDescData []byte
)

func file_domain_Info_proto_rawDescGZIP() []byte {
	file_domain_Info_proto_rawDescOnce.Do(func() {
		file_domain_Info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_Info_proto_rawDesc), len(file_domain_Info_proto_rawDesc)))
	})
	return file_domain_Info_proto_rawDescData
}

var file_domain_Info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_Info_proto_goTypes = []any{
	(*Info)(nil), // 0: domain.Info
}
var file_domain_Info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_Info_proto_init() }
func file_domain_Info_proto_init() {
	if File_domain_Info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_Info_proto_rawDesc), len(file_domain_Info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_Info_proto_goTypes,
		DependencyIndexes: file_domain_Info_proto_depIdxs,
		MessageInfos:      file_domain_Info_proto_msgTypes,
	}.Build()
	File_domain_Info_proto = out.File
	file_domain_Info_proto_goTypes = nil
	file_domain_Info_proto_depIdxs = nil
}
