// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: domain/paymentMean.proto

package domain

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	Iban          string                 `protobuf:"bytes,2,opt,name=iban,proto3" json:"iban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_domain_paymentMean_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paymentMean_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_domain_paymentMean_proto_rawDescGZIP(), []int{0}
}

func (x *BankAccount) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *BankAccount) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

type BillingAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	HouseNumber   *string                `protobuf:"bytes,3,opt,name=houseNumber,proto3,oneof" json:"houseNumber,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	PostOfficeBox *string                `protobuf:"bytes,5,opt,name=postOfficeBox,proto3,oneof" json:"postOfficeBox,omitempty"`
	Street        *string                `protobuf:"bytes,6,opt,name=street,proto3,oneof" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingAddress) Reset() {
	*x = BillingAddress{}
	mi := &file_domain_paymentMean_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingAddress) ProtoMessage() {}

func (x *BillingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_domain_paymentMean_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingAddress.ProtoReflect.Descriptor instead.
func (*BillingAddress) Descriptor() ([]byte, []int) {
	return file_domain_paymentMean_proto_rawDescGZIP(), []int{1}
}

func (x *BillingAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *BillingAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *BillingAddress) GetHouseNumber() string {
	if x != nil && x.HouseNumber != nil {
		return *x.HouseNumber
	}
	return ""
}

func (x *BillingAddress) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *BillingAddress) GetPostOfficeBox() string {
	if x != nil && x.PostOfficeBox != nil {
		return *x.PostOfficeBox
	}
	return ""
}

func (x *BillingAddress) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

var File_domain_paymentMean_proto protoreflect.FileDescriptor

const file_domain_paymentMean_proto_rawDesc = "" +
	"\n" +
	"\x18domain/paymentMean.proto\x12\x06domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"9\n" +
	"\vBankAccount\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x12\x12\n" +
	"\x04iban\x18\x02 \x01(\tR\x04iban\"\x8c\x06\n" +
	"\x0eBillingAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12%\n" +
	"\vhouseNumber\x18\x03 \x01(\tH\x00R\vhouseNumber\x88\x01\x01\x12\x10\n" +
	"\x03zip\x18\x04 \x01(\tR\x03zip\x12)\n" +
	"\rpostOfficeBox\x18\x05 \x01(\tH\x01R\rpostOfficeBox\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x06 \x01(\tH\x02R\x06street\x88\x01\x01:\x9d\x04\xbaH\x99\x04\x1a\x7f\n" +
	"\x1cBillingAddress.CountryLength\x12\x16Country size must be 2\x1aG!(size(this.country) == 2)? 'Country must be 2 letters long eg. DE': ''\x1a\xcd\x01\n" +
	"$BillingAddress.streetOrPostOfficeBox\x128Either street or postOfficeBox must be set, but not both\x1akhas(this.street) == has(this.postOfficeBox)? 'Either street or postOfficeBox must be set, but not both': ''\x1a\xc5\x01\n" +
	"#BillingAddress.StreetAndHouseNumber\x12'Both street and houseNumber must be set\x1auhas(this.street) != has(this.houseNumber)? 'Both street and houseNumber must be set if it is not a postOfficeBox': ''B\x0e\n" +
	"\f_houseNumberB\x10\n" +
	"\x0e_postOfficeBoxB\t\n" +
	"\a_streetB\n" +
	"Z\b./domainb\x06proto3"

var (
	file_domain_paymentMean_proto_rawDescOnce sync.Once
	file_domain_paymentMean_proto_rawDescData []byte
)

func file_domain_paymentMean_proto_rawDescGZIP() []byte {
	file_domain_paymentMean_proto_rawDescOnce.Do(func() {
		file_domain_paymentMean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_paymentMean_proto_rawDesc), len(file_domain_paymentMean_proto_rawDesc)))
	})
	return file_domain_paymentMean_proto_rawDescData
}

var file_domain_paymentMean_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_paymentMean_proto_goTypes = []any{
	(*BankAccount)(nil),    // 0: domain.BankAccount
	(*BillingAddress)(nil), // 1: domain.BillingAddress
}
var file_domain_paymentMean_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_paymentMean_proto_init() }
func file_domain_paymentMean_proto_init() {
	if File_domain_paymentMean_proto != nil {
		return
	}
	file_domain_paymentMean_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_paymentMean_proto_rawDesc), len(file_domain_paymentMean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_paymentMean_proto_goTypes,
		DependencyIndexes: file_domain_paymentMean_proto_depIdxs,
		MessageInfos:      file_domain_paymentMean_proto_msgTypes,
	}.Build()
	File_domain_paymentMean_proto = out.File
	file_domain_paymentMean_proto_goTypes = nil
	file_domain_paymentMean_proto_depIdxs = nil
}
