// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: domain/signupStatus.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubJobStatusEnum int32

const (
	SubJobStatusEnum_SUB_JOB_STATUS_PENDING     SubJobStatusEnum = 0
	SubJobStatusEnum_SUB_JOB_STATUS_IN_PROGRESS SubJobStatusEnum = 1
	SubJobStatusEnum_SUB_JOB_STATUS_COMPLETED   SubJobStatusEnum = 2
	SubJobStatusEnum_SUB_JOB_STATUS_FAILED      SubJobStatusEnum = 3
)

// Enum value maps for SubJobStatusEnum.
var (
	SubJobStatusEnum_name = map[int32]string{
		0: "SUB_JOB_STATUS_PENDING",
		1: "SUB_JOB_STATUS_IN_PROGRESS",
		2: "SUB_JOB_STATUS_COMPLETED",
		3: "SUB_JOB_STATUS_FAILED",
	}
	SubJobStatusEnum_value = map[string]int32{
		"SUB_JOB_STATUS_PENDING":     0,
		"SUB_JOB_STATUS_IN_PROGRESS": 1,
		"SUB_JOB_STATUS_COMPLETED":   2,
		"SUB_JOB_STATUS_FAILED":      3,
	}
)

func (x SubJobStatusEnum) Enum() *SubJobStatusEnum {
	p := new(SubJobStatusEnum)
	*p = x
	return p
}

func (x SubJobStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubJobStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_signupStatus_proto_enumTypes[0].Descriptor()
}

func (SubJobStatusEnum) Type() protoreflect.EnumType {
	return &file_domain_signupStatus_proto_enumTypes[0]
}

func (x SubJobStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubJobStatusEnum.Descriptor instead.
func (SubJobStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_domain_signupStatus_proto_rawDescGZIP(), []int{0}
}

type SignupStatusEnum int32

const (
	SignupStatusEnum_SIGNUP_STATUS_PENDING     SignupStatusEnum = 0
	SignupStatusEnum_SIGNUP_STATUS_IN_PROGRESS SignupStatusEnum = 1
	SignupStatusEnum_SIGNUP_STATUS_COMPLETED   SignupStatusEnum = 2
	SignupStatusEnum_SIGNUP_STATUS_FAILED      SignupStatusEnum = 3
)

// Enum value maps for SignupStatusEnum.
var (
	SignupStatusEnum_name = map[int32]string{
		0: "SIGNUP_STATUS_PENDING",
		1: "SIGNUP_STATUS_IN_PROGRESS",
		2: "SIGNUP_STATUS_COMPLETED",
		3: "SIGNUP_STATUS_FAILED",
	}
	SignupStatusEnum_value = map[string]int32{
		"SIGNUP_STATUS_PENDING":     0,
		"SIGNUP_STATUS_IN_PROGRESS": 1,
		"SIGNUP_STATUS_COMPLETED":   2,
		"SIGNUP_STATUS_FAILED":      3,
	}
)

func (x SignupStatusEnum) Enum() *SignupStatusEnum {
	p := new(SignupStatusEnum)
	*p = x
	return p
}

func (x SignupStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignupStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_signupStatus_proto_enumTypes[1].Descriptor()
}

func (SignupStatusEnum) Type() protoreflect.EnumType {
	return &file_domain_signupStatus_proto_enumTypes[1]
}

func (x SignupStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignupStatusEnum.Descriptor instead.
func (SignupStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_domain_signupStatus_proto_rawDescGZIP(), []int{1}
}

type SignupInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignupId          string                 `protobuf:"bytes,1,opt,name=signupId,proto3" json:"signupId,omitempty"`
	SignupData        *Signup                `protobuf:"bytes,2,opt,name=signupData,proto3" json:"signupData,omitempty"`
	TrackId           string                 `protobuf:"bytes,11,opt,name=trackId,proto3" json:"trackId,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,12,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	CreditCheck       SubJobStatusEnum       `protobuf:"varint,30,opt,name=CreditCheck,proto3,enum=domain.SubJobStatusEnum" json:"CreditCheck,omitempty"`
	AddressValidation SubJobStatusEnum       `protobuf:"varint,31,opt,name=AddressValidation,proto3,enum=domain.SubJobStatusEnum" json:"AddressValidation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignupInfo) Reset() {
	*x = SignupInfo{}
	mi := &file_domain_signupStatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupInfo) ProtoMessage() {}

func (x *SignupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_domain_signupStatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupInfo.ProtoReflect.Descriptor instead.
func (*SignupInfo) Descriptor() ([]byte, []int) {
	return file_domain_signupStatus_proto_rawDescGZIP(), []int{0}
}

func (x *SignupInfo) GetSignupId() string {
	if x != nil {
		return x.SignupId
	}
	return ""
}

func (x *SignupInfo) GetSignupData() *Signup {
	if x != nil {
		return x.SignupData
	}
	return nil
}

func (x *SignupInfo) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *SignupInfo) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SignupInfo) GetCreditCheck() SubJobStatusEnum {
	if x != nil {
		return x.CreditCheck
	}
	return SubJobStatusEnum_SUB_JOB_STATUS_PENDING
}

func (x *SignupInfo) GetAddressValidation() SubJobStatusEnum {
	if x != nil {
		return x.AddressValidation
	}
	return SubJobStatusEnum_SUB_JOB_STATUS_PENDING
}

var File_domain_signupStatus_proto protoreflect.FileDescriptor

const file_domain_signupStatus_proto_rawDesc = "" +
	"\n" +
	"\x19domain/signupStatus.proto\x12\x06domain\x1a\x13domain/signup.proto\"\x9c\x02\n" +
	"\n" +
	"signupInfo\x12\x1a\n" +
	"\bsignupId\x18\x01 \x01(\tR\bsignupId\x12.\n" +
	"\n" +
	"signupData\x18\x02 \x01(\v2\x0e.domain.SignupR\n" +
	"signupData\x12\x18\n" +
	"\atrackId\x18\v \x01(\tR\atrackId\x12$\n" +
	"\rcorrelationId\x18\f \x01(\tR\rcorrelationId\x12:\n" +
	"\vCreditCheck\x18\x1e \x01(\x0e2\x18.domain.SubJobStatusEnumR\vCreditCheck\x12F\n" +
	"\x11AddressValidation\x18\x1f \x01(\x0e2\x18.domain.SubJobStatusEnumR\x11AddressValidation*\x87\x01\n" +
	"\x10SubJobStatusEnum\x12\x1a\n" +
	"\x16SUB_JOB_STATUS_PENDING\x10\x00\x12\x1e\n" +
	"\x1aSUB_JOB_STATUS_IN_PROGRESS\x10\x01\x12\x1c\n" +
	"\x18SUB_JOB_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15SUB_JOB_STATUS_FAILED\x10\x03*\x83\x01\n" +
	"\x10SignupStatusEnum\x12\x19\n" +
	"\x15SIGNUP_STATUS_PENDING\x10\x00\x12\x1d\n" +
	"\x19SIGNUP_STATUS_IN_PROGRESS\x10\x01\x12\x1b\n" +
	"\x17SIGNUP_STATUS_COMPLETED\x10\x02\x12\x18\n" +
	"\x14SIGNUP_STATUS_FAILED\x10\x03B\n" +
	"Z\b./domainb\x06proto3"

var (
	file_domain_signupStatus_proto_rawDescOnce sync.Once
	file_domain_signupStatus_proto_rawDescData []byte
)

func file_domain_signupStatus_proto_rawDescGZIP() []byte {
	file_domain_signupStatus_proto_rawDescOnce.Do(func() {
		file_domain_signupStatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_signupStatus_proto_rawDesc), len(file_domain_signupStatus_proto_rawDesc)))
	})
	return file_domain_signupStatus_proto_rawDescData
}

var file_domain_signupStatus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_signupStatus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_signupStatus_proto_goTypes = []any{
	(SubJobStatusEnum)(0), // 0: domain.SubJobStatusEnum
	(SignupStatusEnum)(0), // 1: domain.SignupStatusEnum
	(*SignupInfo)(nil),    // 2: domain.signupInfo
	(*Signup)(nil),        // 3: domain.Signup
}
var file_domain_signupStatus_proto_depIdxs = []int32{
	3, // 0: domain.signupInfo.signupData:type_name -> domain.Signup
	0, // 1: domain.signupInfo.CreditCheck:type_name -> domain.SubJobStatusEnum
	0, // 2: domain.signupInfo.AddressValidation:type_name -> domain.SubJobStatusEnum
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_signupStatus_proto_init() }
func file_domain_signupStatus_proto_init() {
	if File_domain_signupStatus_proto != nil {
		return
	}
	file_domain_signup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_signupStatus_proto_rawDesc), len(file_domain_signupStatus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_signupStatus_proto_goTypes,
		DependencyIndexes: file_domain_signupStatus_proto_depIdxs,
		EnumInfos:         file_domain_signupStatus_proto_enumTypes,
		MessageInfos:      file_domain_signupStatus_proto_msgTypes,
	}.Build()
	File_domain_signupStatus_proto = out.File
	file_domain_signupStatus_proto_goTypes = nil
	file_domain_signupStatus_proto_depIdxs = nil
}
