---
openapi: "3.1.1"
jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema"
info:
  title: POC Event Signup
  description: Example API for event driven signup
  version: latest
  license:
    name: unlicense
    url: "http://unlicense.org/"
  contact:
    name: Julian Bensch
    url: "https://csr.sh/contact"

servers:
  - url: "/"
    description: This server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  $ref: "./resources/_index.yml"
