---
openapi: "3.1.0"
info:
  title: Example Event Driven Service with Protoflow and APIWeaver
  description: Example API for an event driven service using Protoflow and APIWeaver.
  version: latest
  license:
    name: unlicense
    url: "http://unlicense.org/"
  contact:
    name: Julian Bensch
    url: "https://csr.sh/contact"

servers:
  - url: "/"
    description: This server

tags:
  - name: APIInfo
    description: Endpoints for retrieving API metadata and documentation
  - name: Examples
    description: Example endpoints demonstrating the event-driven workflow
  - name: Probes
    description: Kubernetes health and readiness probes

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  $ref: "./resources/_index.yml"
