name: Build Release & Push Image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  lint-api:
    name: lint-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install -g @redocly/cli
      - run: redocly lint api/api.yml

  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "src/go.mod"
      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 5m
          working-directory: src
